
   
name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: ls -a ${{ github.workspace }}
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: -avzr #"-rltgoDzvO"
          SOURCE: "."
          REMOTE_HOST: renamon.fedorg.net
          REMOTE_USER: dvoell
          TARGET: '/home/dvoell/testass/'
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
           host: renamon.fedorg.net
           username: dvoell
           key: ${{ secrets.SERVER_SSH_KEY }}
           script: |
            cd testass/
            ./docker_cumpot.sh
         
